FROM ubuntu:14.04
LABEL author="DC Morrison"
ENV REFRESHED_AT=2022-03-11
RUN apt-get update
RUN apt-get -y -q install nginx
RUN mkdir -p /var/www/html
ADD nginx/global.conf /etc/nginx/conf.d/
ADD nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
